host: '192.168.0.104'
port: 8848
namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'pro'

# 存放jwt的key统一配置----后续可能直接迁移到nacos配置中
# jwt: 
#   key: '76hfhfhfhhrtg5'

# sms:
#   key: '8a216daa7d7c4c0f9c0f7c5c5f7a0a0a'
#   secret: 'f7c5c5f7a0a0a'
# redis:
#   host: '192.168.1.103'
#   port: 6379
