// Code generated by ast/codegen.go. DO NOT EDIT.
// 通过 go generate 自动生成，请勿手动修改此文件。

package code

import "mxshop/pkg/errors"

// coder 实现 errors.Coder 接口，用于向 pkg/errors 注册错误码
type coder struct {
	code int    // 业务错误码（6位）
	http int    // 对应 HTTP 状态码
	ext  string // 面向用户的错误描述
	ref  string // 参考文档链接
}

func (c coder) Code() int         { return c.code }
func (c coder) HTTPStatus() int   { return c.http }
func (c coder) String() string    { return c.ext }
func (c coder) Reference() string { return c.ref }

// register 是注册错误码的快捷方法
func register(code, httpStatus int, message, ref string) {
	errors.MustRegister(coder{
		code: code,
		http: httpStatus,
		ext:  message,
		ref:  ref,
	})
}

func init() {
	register(ErrGoodsNotFound, 404, "商品不存在", "")
	register(ErrGoodsSoldOut, 400, "商品已下架", "")
	register(ErrGoodsCreateFail, 500, "商品创建失败", "")
	register(ErrGoodsStockNotEnough, 400, "商品库存不足", "")
	register(ErrUserNotFound, 404, "用户不存在", "")
	register(ErrUserAlreadyExist, 409, "用户已存在", "")
	register(ErrUserLoginFail, 401, "登录失败", "")
	register(ErrSuccess, 200, "OK", "")
	register(ErrUnknown, 500, "未知错误", "")
	register(ErrParamInvalid, 400, "参数无效", "")
	register(ErrValidation, 400, "数据校验失败", "")
	register(ErrBind, 400, "请求体解析失败", "")
	register(ErrTooManyRequests, 429, "请求频繁", "")
	register(ErrDatabaseError, 500, "数据库错误", "")
	register(ErrDatabaseRecordNotFound, 404, "记录不存在", "")
	register(ErrDatabaseDuplicate, 409, "数据重复", "")
	register(ErrDatabaseExec, 500, "SQL执行失败", "")
	register(ErrDatabaseTransaction, 500, "事务失败", "")
	register(ErrTokenInvalid, 401, "Token无效", "")
	register(ErrTokenTimeout, 401, "Token过期", "")
	register(ErrTokenGenerate, 500, "Token生成失败", "")
	register(ErrPermissionDenied, 403, "权限不足", "")
	register(ErrPasswordInvalid, 400, "密码错误", "")
	register(ErrEncrypt, 500, "加密失败", "")
	register(ErrDecrypt, 500, "解密失败", "")
	register(ErrSignInvalid, 400, "签名无效", "")
	register(ErrEncode, 500, "编码失败", "")
	register(ErrDecode, 500, "解码失败", "")
}
