package generator

import (
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const (
	ginPkg  = protogen.GoImportPath("github.com/gin-gonic/gin")
	httpPkg = protogen.GoImportPath("net/http")
)

var methodSets = make(map[string]int)

// GenerateFile 函数
// 作用：根据 proto 文件，生成对应的 Gin 代码文件
// gen ：protoc 插件工具
// file：当前被解析的 .proto 文件
func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	//设置生成的文件名，文件名会被protoc使用，生成的文件会被放在响应的目录下
	// 例子：
	// proto 文件叫 hello.proto
	// 生成的文件名叫：hello_gin.pb.go
	filename := file.GeneratedFilenamePrefix + "_gin.pb.go"
	// 创建一个新的“文件写入器”
	// 作用：用来往文件里一行一行写代码
	// proto文件中的option go_package = "./api/v1;v1"; ---> file.GoImportPath就是./api/v1
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	//该注释会被go的ide识别到， 表示该文件是自动生成的，尽量不要修改
	// ====================== 2. 写文件头部固定内容 ======================
	// 写注释：告诉别人这是自动生成的，不要手动改
	g.P("// Code generated by protoc-gen-gin. DO NOT EDIT.")
	g.P()
	// 写 package 名
	// 例子：file.GoImportPath就是./api/v1，file.GoPackageName就是v1
	g.P("package ", file.GoPackageName)

	//该函数是注册全局的packge 的内容，但是此时不会写入
	// ====================== 3. 自动导入需要的包 ======================
	// 这两句非常关键！
	// 作用：告诉插件，代码里要用到 gin 和 net/http
	// 插件会自动在文件顶部生成 import 语句
	g.QualifiedGoIdent(ginPkg.Ident("")) // 等价于 import "github.com/gin-gonic/gin"
	g.QualifiedGoIdent(httpPkg.Ident(""))
	// ====================== 4. 遍历 proto 里的所有 service ======================
	// 一个 proto 文件可能有多个服务
	for _, service := range file.Services {
		// 给每个服务生成 Gin 代码（注册路由、handler等）
		genService(file, g, service)
	}

	//自己写文件看结果
	// ====================== 下面是你自己测试用的代码 ======================
	// 你想自己把生成的内容写到本地文件里看结果
	//f, err := os.Create("api_gin.pb.go")
	//
	//if err != nil {
	//	log.Fatal(err)
	//}
	//
	//defer f.Close()
	//
	//contentStr, _ := g.Content()
	//_, _ = f.WriteString(string(contentStr))
	// 返回生成好的文件给 protoc
	return g
}

func genService(file *protogen.File, g *protogen.GeneratedFile, s *protogen.Service) {
	// HTTP Server ：直接引用的是./template.go中的service类型
	sd := &service{
		Name:     s.GoName,
		FullName: string(s.Desc.FullName()),
	}

	for _, method := range s.Methods {
		sd.Methods = append(sd.Methods, genMethod(method)...)
	}

	text := sd.execute()
	g.P(text)
}

func genMethod(m *protogen.Method) []*method {
	var methods []*method

	// 存在 http rule 配置
	// options
	rule, ok := proto.GetExtension(m.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
	if rule != nil && ok {
		//for _, bind := range rule.AdditionalBindings {
		//	methods = append(methods, buildHTTPRule(m, bind))
		//}

		methods = append(methods, buildHTTPRule(m, rule))
		return methods
	}

	methods = append(methods, defaultMethod(m))
	return methods
}

func defaultMethod(m *protogen.Method) *method {
	// TODO path
	// $prefix + / + ${package}.${service} + / + ${method}
	// /api/demo.v0.Demo/GetName
	md := buildMethodDesc(m, "POST", "")
	md.Body = "*"
	return md
}

func buildHTTPRule(m *protogen.Method, rule *annotations.HttpRule) *method {
	var path, method string
	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		path = pattern.Get
		method = "GET"
	case *annotations.HttpRule_Put:
		path = pattern.Put
		method = "PUT"
	case *annotations.HttpRule_Post:
		path = pattern.Post
		method = "POST"
	case *annotations.HttpRule_Delete:
		path = pattern.Delete
		method = "DELETE"
	case *annotations.HttpRule_Patch:
		path = pattern.Patch
		method = "PATCH"
	case *annotations.HttpRule_Custom:
		path = pattern.Custom.Path
		method = pattern.Custom.Kind
	}

	md := buildMethodDesc(m, method, path)
	return md
}

func buildMethodDesc(m *protogen.Method, httpMethod string, path string) *method {
	defer func() { methodSets[m.GoName]++ }()

	md := &method{
		Name:    m.GoName,
		Num:     methodSets[m.GoName],
		Request: m.Input.GoIdent.GoName,
		Reply:   m.Output.GoIdent.GoName,
		Path:    path,
		Method:  httpMethod,
	}

	md.initPathParams()
	return md
}
