// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: helloworld.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_helloworld_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 1是编号 ，不是值
	Age   int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Data  []*HelloRequest_Result `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"` // 列表、数组、多个值 都用 repeated
	// 使用枚举类型
	G Gender `protobuf:"varint,4,opt,name=g,proto3,enum=Gender" json:"g,omitempty"`
	// 使用map类型
	Mp map[string]string `protobuf:"bytes,5,rep,name=mp,proto3" json:"mp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 使用内置的时间戳类型
	AddTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=addTime,proto3" json:"addTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *HelloRequest) GetData() []*HelloRequest_Result {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HelloRequest) GetG() Gender {
	if x != nil {
		return x.G
	}
	return Gender_MALE
}

func (x *HelloRequest) GetMp() map[string]string {
	if x != nil {
		return x.Mp
	}
	return nil
}

func (x *HelloRequest) GetAddTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AddTime
	}
	return nil
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest_Result) Reset() {
	*x = HelloRequest_Result{}
	mi := &file_helloworld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest_Result) ProtoMessage() {}

func (x *HelloRequest_Result) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest_Result.ProtoReflect.Descriptor instead.
func (*HelloRequest_Result) Descriptor() ([]byte, []int) {
	return file_helloworld_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HelloRequest_Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest_Result) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_helloworld_proto protoreflect.FileDescriptor

const file_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x10helloworld.proto\x1a\n" +
	"base.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x02\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.HelloRequest.ResultR\x04data\x12\x15\n" +
	"\x01g\x18\x04 \x01(\x0e2\a.GenderR\x01g\x12%\n" +
	"\x02mp\x18\x05 \x03(\v2\x15.HelloRequest.MpEntryR\x02mp\x124\n" +
	"\aaddTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aaddTime\x1a.\n" +
	"\x06Result\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x1a5\n" +
	"\aMpEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x1e\n" +
	"\x06Gender\x12\b\n" +
	"\x04MALE\x10\x00\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x012X\n" +
	"\aGreeter\x12&\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\x12%\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x05.PongB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_helloworld_proto_rawDescOnce sync.Once
	file_helloworld_proto_rawDescData []byte
)

func file_helloworld_proto_rawDescGZIP() []byte {
	file_helloworld_proto_rawDescOnce.Do(func() {
		file_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)))
	})
	return file_helloworld_proto_rawDescData
}

var file_helloworld_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_proto_goTypes = []any{
	(Gender)(0),                   // 0: Gender
	(*HelloRequest)(nil),          // 1: HelloRequest
	(*HelloReply)(nil),            // 2: HelloReply
	(*HelloRequest_Result)(nil),   // 3: HelloRequest.Result
	nil,                           // 4: HelloRequest.MpEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
	(*Pong)(nil),                  // 7: Pong
}
var file_helloworld_proto_depIdxs = []int32{
	3, // 0: HelloRequest.data:type_name -> HelloRequest.Result
	0, // 1: HelloRequest.g:type_name -> Gender
	4, // 2: HelloRequest.mp:type_name -> HelloRequest.MpEntry
	5, // 3: HelloRequest.addTime:type_name -> google.protobuf.Timestamp
	1, // 4: Greeter.SayHello:input_type -> HelloRequest
	6, // 5: Greeter.Ping:input_type -> google.protobuf.Empty
	2, // 6: Greeter.SayHello:output_type -> HelloReply
	7, // 7: Greeter.Ping:output_type -> Pong
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_helloworld_proto_init() }
func file_helloworld_proto_init() {
	if File_helloworld_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_proto_rawDesc), len(file_helloworld_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_proto_goTypes,
		DependencyIndexes: file_helloworld_proto_depIdxs,
		EnumInfos:         file_helloworld_proto_enumTypes,
		MessageInfos:      file_helloworld_proto_msgTypes,
	}.Build()
	File_helloworld_proto = out.File
	file_helloworld_proto_goTypes = nil
	file_helloworld_proto_depIdxs = nil
}
