// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock is a generated GoMock package.
package mock

import (
	mock "GoStart/mock"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserData is a mock of UserData interface.
type MockUserData struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataMockRecorder
}

// MockUserDataMockRecorder is the mock recorder for MockUserData.
type MockUserDataMockRecorder struct {
	mock *MockUserData
}

// NewMockUserData creates a new mock instance.
func NewMockUserData(ctrl *gomock.Controller) *MockUserData {
	mock := &MockUserData{ctrl: ctrl}
	mock.recorder = &MockUserDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserData) EXPECT() *MockUserDataMockRecorder {
	return m.recorder
}

// GetUserByMobile mocks base method.
// 作用：真正被调用的 mock 方法
// 当你的业务代码调用 us.Db.GetUserByMobile() 时
// 实际跑的就是这个方法
// 它会去 gomock 控制器里拿你预设的返回值
// 然后返回给业务代码
func (m *MockUserData) GetUserByMobile(ctx context.Context, mobile string) (mock.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByMobile", ctx, mobile)
	ret0, _ := ret[0].(mock.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByMobile indicates an expected call of GetUserByMobile.
// 写 EXPECT 打桩用的方法（测试时用）
func (mr *MockUserDataMockRecorder) GetUserByMobile(ctx, mobile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByMobile", reflect.TypeOf((*MockUserData)(nil).GetUserByMobile), ctx, mobile)
}
